---
title: "Experience"
---

### [LinkedIn](https://www.linkedin.com/in/madison-goldrich-920327149/)


## Education

#### Columbia University Mailman School of Public Health
*Master of Public Health in Sociomedical Sciences, Certificate in Applied Biostatistics and Public Health Data Science*

* Expected Degree Conferral May 2024

#### University of Virginia, School of Engineering and Applied Science
*Bachelor of Science in Biomedical Engineering, Minor in Government*

* Degree Conferred May 2020


## Professional Experience

#### Columbia University Mailman School of Public Health
*Lead Graduate Teaching Assistant, July 2023 - Present*

* MPH Core Curriculum - Quantitative Research Methods and Applications

#### National Human Genome Research Institute, National Institutes of Health
*Scientific Program Analyst, July 2020 - July 2022*

* Provided support for 5 genomics programs and consortia funded by NHGRI and NIH: organized meetings and recorded minutes, corresponded with grantees, and analyzed scientific and programmatic information
* Reviewed approx. 100 publications per month of genomic medicine implementation advances and resources; proposed 5-10 for potential inclusion in an annual review of notable accomplishments
* Organized and attended Genomic Medicine XIII conference to develop a research strategy on the use of genomic-based clinical informatics resources to improve the detection, treatment, and reporting of genetic disorders in clinical settings

#### School of Engineering and Applied Science, University of Virginia
*Undergraduate Teaching Assistant, August 2018 - May 2020*

* Courses: Biomedical Engineering Design & Discovery, Applied Probability & Statistics, Ordinary Differential Equations
* Graded an average of 50 assignments per week, fielded student questions during class, and held weekly office hours
